import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";

import "./globals.css";

type Props = {
	children: React.ReactNode;
};

export const metadata: Metadata = {
	title: "Sellswords Initiative",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: Props) {
	return (
		<html lang="en" className="h-full">
			<body className="h-full">
				<NextIntlClientProvider>{children}</NextIntlClientProvider>
			</body>
		</html>
	);
}
